[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "blackhat"
version = "1.0.0"
description = "Python for Penetration Testers"

[project.urls]
homepage = "https://github.com/wilsonify/blackhat-python3"

[tool.setuptools]
packages = ["blackhat"]